// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PersonalAccountServiceClient is the client API for PersonalAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersonalAccountServiceClient interface {
	PersonalAccount(ctx context.Context, in *PersonalAccountRequest, opts ...grpc.CallOption) (*PersonalAccountResponse, error)
}

type personalAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonalAccountServiceClient(cc grpc.ClientConnInterface) PersonalAccountServiceClient {
	return &personalAccountServiceClient{cc}
}

func (c *personalAccountServiceClient) PersonalAccount(ctx context.Context, in *PersonalAccountRequest, opts ...grpc.CallOption) (*PersonalAccountResponse, error) {
	out := new(PersonalAccountResponse)
	err := c.cc.Invoke(ctx, "/api.PersonalAccountService/PersonalAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonalAccountServiceServer is the server API for PersonalAccountService service.
// All implementations must embed UnimplementedPersonalAccountServiceServer
// for forward compatibility
type PersonalAccountServiceServer interface {
	PersonalAccount(context.Context, *PersonalAccountRequest) (*PersonalAccountResponse, error)
	mustEmbedUnimplementedPersonalAccountServiceServer()
}

// UnimplementedPersonalAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPersonalAccountServiceServer struct {
}

func (UnimplementedPersonalAccountServiceServer) PersonalAccount(context.Context, *PersonalAccountRequest) (*PersonalAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonalAccount not implemented")
}
func (UnimplementedPersonalAccountServiceServer) mustEmbedUnimplementedPersonalAccountServiceServer() {
}

// UnsafePersonalAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersonalAccountServiceServer will
// result in compilation errors.
type UnsafePersonalAccountServiceServer interface {
	mustEmbedUnimplementedPersonalAccountServiceServer()
}

func RegisterPersonalAccountServiceServer(s grpc.ServiceRegistrar, srv PersonalAccountServiceServer) {
	s.RegisterService(&PersonalAccountService_ServiceDesc, srv)
}

func _PersonalAccountService_PersonalAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonalAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonalAccountServiceServer).PersonalAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PersonalAccountService/PersonalAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonalAccountServiceServer).PersonalAccount(ctx, req.(*PersonalAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersonalAccountService_ServiceDesc is the grpc.ServiceDesc for PersonalAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersonalAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.PersonalAccountService",
	HandlerType: (*PersonalAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PersonalAccount",
			Handler:    _PersonalAccountService_PersonalAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

// TransferMarketServiceClient is the client API for TransferMarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferMarketServiceClient interface {
	TransferSell(ctx context.Context, in *TransferSellRequest, opts ...grpc.CallOption) (*Empty, error)
}

type transferMarketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferMarketServiceClient(cc grpc.ClientConnInterface) TransferMarketServiceClient {
	return &transferMarketServiceClient{cc}
}

func (c *transferMarketServiceClient) TransferSell(ctx context.Context, in *TransferSellRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.TransferMarketService/TransferSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferMarketServiceServer is the server API for TransferMarketService service.
// All implementations must embed UnimplementedTransferMarketServiceServer
// for forward compatibility
type TransferMarketServiceServer interface {
	TransferSell(context.Context, *TransferSellRequest) (*Empty, error)
	mustEmbedUnimplementedTransferMarketServiceServer()
}

// UnimplementedTransferMarketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransferMarketServiceServer struct {
}

func (UnimplementedTransferMarketServiceServer) TransferSell(context.Context, *TransferSellRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferSell not implemented")
}
func (UnimplementedTransferMarketServiceServer) mustEmbedUnimplementedTransferMarketServiceServer() {}

// UnsafeTransferMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferMarketServiceServer will
// result in compilation errors.
type UnsafeTransferMarketServiceServer interface {
	mustEmbedUnimplementedTransferMarketServiceServer()
}

func RegisterTransferMarketServiceServer(s grpc.ServiceRegistrar, srv TransferMarketServiceServer) {
	s.RegisterService(&TransferMarketService_ServiceDesc, srv)
}

func _TransferMarketService_TransferSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferSellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferMarketServiceServer).TransferSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TransferMarketService/TransferSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferMarketServiceServer).TransferSell(ctx, req.(*TransferSellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferMarketService_ServiceDesc is the grpc.ServiceDesc for TransferMarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferMarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TransferMarketService",
	HandlerType: (*TransferMarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferSell",
			Handler:    _TransferMarketService_TransferSell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
